#feature/캘린더-UI epic clone -> commit
PUE-AI-ChatBot/PUE-FE pull request #7
Opened 2022-09-03 16:39 UTC by onejuice98

## Description
 * 캘린더-UI 프로토타입 개발
   - PUE 캐릭터 UI (message 포함) 
   - react-calendar 활용 달력 UI (diary.tsx)
   - 달력 내 해당일 감정 표시 가능
 * 기존 tailwind css 에서 MUI, style sheet 활용으로 수정
 * 디렉토리 구조 수정

## Related Issue
 * 달력에서 날짜 클릭 시 나오는 변화에 대해서 토의 필요
  - hover, active
  - chat log 
  - 차트
 * 디자인에 대한 토의 필요
  - emoji 가 아닌 그림으로 할 것 인지에 대해

## Motivation and Context
* 프로토 타입이고, 정말 틀만 잡았습니다. 
* 달력의 날짜에 들어갈 그림은 그날의 감정이 들어 갈 것입니다.
 - application 의 diary, DayResults.ts 에 목 데이터를 넣었고, 구조적인 리뷰(type, function)가 좀 많이 필요할 듯합니다..
 - Character BOX는 빈 공간으로 추후 이미지, 영상이 들어가고 message 또한 사용자의 주 된 감정에 대해서 설명해주는 칸이 될 것입니다.

## How Has This Been Tested?
- Please describe in detail how you tested your changes.
- Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code, etc.

## Screenshots
![sceenshot](https://user-images.githubusercontent.com/44994011/188280160-8a902434-49eb-463b-8e22-cbb8bbdb96b6.png)

2022-09-04 15:08 UTC, elbica requested changes
front-end 폴더 안에 commit들이 반영 된 것 같습니다. 

제가 폴더 구조 바꾼 commit 이전을 clone 하신 것 같아요 ㅠㅠ
번거로우시겠지만, 다시 한 번 반영 부탁드립니다.

2022-09-04 15:08 UTC, elbica commented on front-end/src/application/chart/MultiSeries.tsx
> +  });
mock 데이터는 따로 mock.ts 같은 파일을 만들어서 모아 두는 것이 가독성이 좋을 것 같습니다 :)

2022-09-04 15:08 UTC, elbica commented on front-end/src/components/diary/index.tsx
> +const Calendar = dynamic(() => import('react-calendar'), { ssr: false });
`react calendar`를 CSR dynamic import로 적용하신 이유가 있을까요?

2022-09-04 15:08 UTC, elbica commented on front-end/src/components/diary/index.tsx
> +import styled from 'styled-components';
이것도 찾아보니 mui에서 내장 style을 지원하네요(default로 emotion입니다)
> import { styled } from '@mui/material/styles'

2022-09-04 15:08 UTC, elbica commented on front-end/src/pages/_app.tsx
> +>>>>>>> c7a78574735642dea61b1ef5e7cc35aa58a145f1:front-end/src/pages/_app.tsx
merge conflict 처리가 잘 안된 것 같습니다!

2022-09-04 15:08 UTC, elbica commented on styles/calendar.css
> +.react-calendar {
mui 내장 style(또는 styled-component)을 사용하지 않고 일반 CSS로 작성하신 이유가 있을까요?

2022-09-06 10:51 UTC, onejuice98 commented on styles/calendar.css
> +.react-calendar {
react calendar 라이브러리를 사용합니다. 따라서 캘린더 내부의 html 태그에 스타일 MUI 등으로 스타일 적용시켜 볼려했으나 다른 방법을 찾을 수가 없어서 일반 css로 작업하였습니다.

2022-09-06 13:12 UTC, elbica commented on styles/calendar.css
> +.react-calendar {
`styled(Calendar)` 로 기존 컴포넌트의 스타일을 변경할 수 있는 것으로 아는데, 혹시 시도해 보셨을까요?

2022-09-06 15:05 UTC, elbica approved these changes

2022-09-08 15:26 UTC, merged